const routeUrls = {
    HOME: '/',
    LOGIN: '/login',
    CRIAR_EVENTO: '/criar-evento',
    EDITAR_EVENTO: '/editar-evento',
    CADASTRO: '/cadastro',
    DASHBOARD: '/dashboard',
    ESCOLHER_GUIA: '/escolher-guia',
    CATALOGO_TRILHA: '/catalogo-trilhas',
    QUESTIONARIO: '/questionario',
    EDITAR_DADOS_AVENTUREIRO: '/editar-dados-aventureiro',
    DADOS_CLIENTE: '/dados-cliente',
    ATIVAR_EVENTO: '/ativar-evento',
    CRIAR_INFOS_ADIC_GUIA: '/infos-adic-guia',
    CATALOGO_TRILHAS_ADM: '/catalogo-trilhas-adm',
    INSCRICAO_TRILHAS: '/inscricao-trilhas',
    ADICIONAR_GUIA: '/adicionar-guia',
    LISTA_CONVITES: '/lista-convites',
    VER_GUIAS:'/ver-guias',
    ESCOLHER_DATA: '/escolher-data',
    AGENDA_GUIA: '/agenda-guia',
    INFOS_ADICIONAIS_GUIA: '/infos-adic-guia',
    ESCOLHER_DATA: '/escolher-data',
    DADOS_GUIA: '/dados-guia',
    AGENDA_AVENTUREIRO: '/agenda-aventureiro',
    VISUALIZAR_GUIAS: '/visualizar-guias',
    RELATORIO_ANAMNESE: '/relatorio-anamnese',
    CONVITE_AVENTUREIRO: '/convite-aventureiro',
    AGENDAMENTO_ANAMNESE: '/agendamento-anamnese',
    DETALHES_EVENTO: '/detalhes-evento',
};

export default routeUrls;
