const routeUrls = {
    HOME: '/',
    LOGIN: '/login',
    CRIAR_EVENTO: '/criar-evento',
    EDITAR_EVENTO: '/editar-evento/:id',
    CADASTRO: '/cadastro',
    DASHBOARD: '/dashboard',
    ESCOLHER_GUIA: '/escolher-guia',
    CATALOGO_TRILHA: '/catalogo-trilhas',
    QUESTIONARIO: '/questionario',
    INFORMACOES_PESSOAIS: '/informacoes-pessoais',
    DADOS_CLIENTE: '/dados-cliente/:id',
    ATIVAR_EVENTO: '/ativar-evento/:id',
    CRIAR_INFOS_ADIC_GUIA: '/infos-adic-guia',
    CATALOGO_TRILHAS_ADM: '/catalogo-trilhas-adm',
    INSCRICAO_TRILHAS: `/inscricao-trilhas/:id`,
    ADICIONAR_GUIA: '/adicionar-guia',
    VER_GUIAS:'/ver-guias',
    ESCOLHER_DATA: '/escolher-data',
    AGENDA_GUIA: '/agenda-guia',
    INFOS_ADICIONAIS_GUIA: '/infos-adic-guia',
    ESCOLHER_DATA: '/escolher-data',
    DADOS_GUIA: '/dados-guia',
    AGENDA_AVENTUREIRO: '/agenda-aventureiro',
    RELATORIO_ANAMNESE: '/relatorio-anamnese/:id',
    AGENDAMENTO_ANAMNESE: '/agendamento-anamnese',
    DETALHES_EVENTO: `/detalhes-evento/${':id'}`,
};

export default routeUrls;
